#!/usr/bin/env python3
"""
GEOMeta Stage 1.6 cross-agent / cross-field validation.

Purpose
-------
Run after Stage 1.5 within-GSE consistency correction and before Stage 2.

Stage 1 uses multiple role-specific annotators:
- Biological context: Disease
- Experimental context: Seq_Type, Organism, RNA_Library, RNA_Source, Tissue,
  Experimental_Setting, Model_Type, etc.
- Perturbation context: GSE_Pert, GSM_Pert, Pert, Pert_Dose, Pert_Freq,
  Pert_Duration, Route_Admin
- Sample metadata context: SampleType, Specimen_Type, Race, Ethnicity, Age,
  Sex, Timepoint, Outcome

This script checks whether fields generated by different agents are logically
compatible. It does not overwrite any annotation. It writes a structured report
and an LLM/human review queue.

Example
-------
PYTHONPATH=. python scripts/stage1_cross_agent_validation.py \
  --input artifacts/outputs/geometa_full_RUN_stage1_qa1_corrected_high_confidence.xlsx \
  --output-dir artifacts/outputs \
  --run-version geometa_full_RUN
"""

from __future__ import annotations

import argparse
import json
import math
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Dict, Iterable, List, Optional, Sequence

import pandas as pd


# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------

EMPTY_TOKENS = {"", "nan", "none", "null", "missing", "blank"}
NA_TOKENS = {"na", "n/a", "not available", "not applicable", "unknown", "not specified"}


def clean_value(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float) and math.isnan(value):
        return ""
    text = str(value).strip()
    if text.lower() in {"nan", "none", "null"}:
        return ""
    return re.sub(r"\s+", " ", text)


def lower_value(value: Any) -> str:
    return clean_value(value).lower()


def is_blank(value: Any) -> bool:
    return lower_value(value) in EMPTY_TOKENS


def is_na_like(value: Any) -> bool:
    return lower_value(value) in EMPTY_TOKENS | NA_TOKENS


def has_any(value: Any, terms: Sequence[str]) -> bool:
    v = lower_value(value)
    return any(t.lower() in v for t in terms)


def eq(value: Any, target: str) -> bool:
    return clean_value(value).casefold() == target.casefold()


def in_set(value: Any, targets: Iterable[str]) -> bool:
    v = clean_value(value).casefold()
    return any(v == str(t).casefold() for t in targets)


def read_table(path: Path, sheet_name: Optional[str] = None) -> pd.DataFrame:
    suffix = path.suffix.lower()
    if suffix in {".xlsx", ".xlsm", ".xls"}:
        return pd.read_excel(path, sheet_name=sheet_name or 0, dtype=str, keep_default_na=False)
    if suffix == ".csv":
        return pd.read_csv(path, dtype=str, keep_default_na=False)
    if suffix in {".tsv", ".txt"}:
        return pd.read_csv(path, sep="\t", dtype=str, keep_default_na=False)
    raise ValueError(f"Unsupported input file type: {path}")


def get(row: pd.Series, col: str) -> str:
    return clean_value(row.get(col, ""))


def get_many(row: pd.Series, cols: Sequence[str]) -> Dict[str, str]:
    return {c: get(row, c) for c in cols}


def value_distribution(df: pd.DataFrame, field: str) -> Dict[str, int]:
    if field not in df.columns:
        return {}
    out: Dict[str, int] = {}
    for val in df[field].map(clean_value):
        key = "<blank>" if is_blank(val) else val
        out[key] = out.get(key, 0) + 1
    return dict(sorted(out.items(), key=lambda kv: (-kv[1], kv[0])))


def compact_context(row: pd.Series, max_chars: int = 1200) -> Dict[str, str]:
    ctx = {}
    for c in ["GSE_Info", "GSM_Info", "Sample_Title", "Title", "Source_Name"]:
        if c in row.index:
            text = get(row, c)
            if len(text) > max_chars:
                text = text[:max_chars] + " ...[truncated]"
            ctx[c] = text
    return ctx


@dataclass(frozen=True)
class ValidationConfig:
    gse_col: str = "GSE_ID"
    gsm_col: str = "GSM_ID"
    max_context_chars: int = 1200
    include_low_severity: bool = False


class IssueWriter:
    def __init__(self, df: pd.DataFrame, config: ValidationConfig):
        self.df = df
        self.config = config
        self.rows: List[Dict[str, Any]] = []
        self._counter = 0

    def add(
        self,
        row: pd.Series,
        rule_id: str,
        rule_name: str,
        severity: str,
        issue_type: str,
        fields: Sequence[str],
        suggested_action: str,
        rationale: str,
        needs_llm_review: bool = True,
        needs_human_review: bool = False,
        suggested_field: str = "",
        suggested_value: str = "",
    ) -> None:
        if severity == "Low" and not self.config.include_low_severity:
            return
        self._counter += 1
        gse_id = get(row, self.config.gse_col)
        gsm_id = get(row, self.config.gsm_col)
        gse_df = self.df[self.df[self.config.gse_col].astype(str).str.strip() == gse_id] if self.config.gse_col in self.df.columns else pd.DataFrame()
        distributions = {f: value_distribution(gse_df, f) for f in fields if f in self.df.columns}

        current_values = get_many(row, fields)
        self.rows.append(
            {
                "Issue_ID": f"CA{self._counter:07d}",
                "GSE_ID": gse_id,
                "GSM_ID": gsm_id,
                "Rule_ID": rule_id,
                "Rule_Name": rule_name,
                "Severity": severity,
                "Issue_Type": issue_type,
                "Fields_Involved": "; ".join(fields),
                "Current_Values_JSON": json.dumps(current_values, ensure_ascii=False),
                "Same_GSE_Distributions_JSON": json.dumps(distributions, ensure_ascii=False),
                "Suggested_Action": suggested_action,
                "Suggested_Field": suggested_field,
                "Suggested_Value": suggested_value,
                "Rationale": rationale,
                "Needs_LLM_Review": "YES" if needs_llm_review else "NO",
                "Needs_Human_Review": "YES" if needs_human_review else "NO",
                "GSE_Info_Snippet": compact_context(row, self.config.max_context_chars).get("GSE_Info", ""),
                "GSM_Info_Snippet": compact_context(row, self.config.max_context_chars).get("GSM_Info", ""),
                "Reviewer_Decision": "",
                "Reviewer_Notes": "",
            }
        )

    def dataframe(self) -> pd.DataFrame:
        return pd.DataFrame(self.rows)


# -----------------------------------------------------------------------------
# Rule sets
# -----------------------------------------------------------------------------

TUMOR_TERMS = [
    "tumor", "tumour", "cancer", "carcinoma", "adenocarcinoma", "sarcoma",
    "leukemia", "lymphoma", "glioma", "melanoma", "neoplasm", "malignant",
    "metastasis", "metastatic",
]
CELL_LINE_MARKERS = ["cell line:", " cell line", "cells:", "hela", "mcf7", "mcf-7", "a549", "hek293", "lncap", "k562"]
FEMALE_TISSUES = ["ovary", "ovarian", "uterus", "uterine", "endometrium", "endometrial", "cervix", "cervical", "placenta", "fallopian"]
MALE_TISSUES = ["prostate", "testis", "testicular", "seminiferous"]


def validate_seq_type_rna_library(row: pd.Series, w: IssueWriter) -> None:
    seq = get(row, "Seq_Type")
    lib = get(row, "RNA_Library")
    if not seq and not lib:
        return

    if eq(seq, "Other") and not is_na_like(lib):
        w.add(
            row,
            "R001",
            "Seq_Type Other conflicts with RNA_Library",
            "High",
            "Cross-agent conflict",
            ["Seq_Type", "RNA_Library"],
            "Review RNA_Library; for non-RNA assays it is usually NA.",
            "Seq_Type is Other but RNA_Library contains a specific RNA library class.",
            suggested_field="RNA_Library",
            suggested_value="NA",
        )

    if in_set(seq, {"SC-RNA", "BULK-RNA"}) and is_blank(lib):
        w.add(
            row,
            "R002",
            "RNA assay has blank RNA_Library",
            "Medium",
            "Missing related field",
            ["Seq_Type", "RNA_Library"],
            "Review RNA_Library using GSE/GSM protocol and same-GSE distribution.",
            "RNA sequencing sample has blank RNA_Library; Stage 1.5 may not fill whole-GSE missing cases.",
            needs_llm_review=True,
        )


def validate_rna_source_tissue_sampletype(row: pd.Series, w: IssueWriter) -> None:
    rna_source = get(row, "RNA_Source")
    tissue = get(row, "Tissue")
    sample_type = get(row, "SampleType")
    specimen = get(row, "Specimen_Type")
    model = get(row, "Model_Type")

    if has_any(rna_source, ["cell line:"]) and not in_set(sample_type, {"Cell Line"}) and not in_set(specimen, {"Cell Line"}):
        w.add(
            row,
            "R010",
            "RNA_Source indicates cell line but SampleType/Specimen_Type do not",
            "High",
            "Cross-agent conflict",
            ["RNA_Source", "SampleType", "Specimen_Type", "Model_Type"],
            "Review SampleType and Specimen_Type against GSM source/name.",
            "RNA_Source uses Cell Line format but sample metadata agent did not classify it as Cell Line.",
            suggested_field="SampleType",
            suggested_value="Cell Line",
        )

    if in_set(sample_type, {"Cell Line"}) and in_set(specimen, {"Primary Tissue", "Isolated Cells", "Fetus", "Tissue Culture"}):
        w.add(
            row,
            "R011",
            "SampleType Cell Line conflicts with Specimen_Type",
            "High",
            "Cross-agent conflict",
            ["SampleType", "Specimen_Type", "RNA_Source", "Model_Type"],
            "Review SampleType/Specimen_Type pair.",
            "SampleType is Cell Line but Specimen_Type suggests directly obtained tissue/cells.",
            needs_human_review=True,
        )

    if in_set(sample_type, {"Patient Specimen"}) and in_set(specimen, {"Cell Line", "Organoid", "PDX"}):
        w.add(
            row,
            "R012",
            "Patient Specimen conflicts with cultured/xenograft Specimen_Type",
            "High",
            "Cross-agent conflict",
            ["SampleType", "Specimen_Type", "RNA_Source", "Model_Type"],
            "Review whether the sample is direct patient material, PDX, organoid, or cell line.",
            "Patient Specimen should not usually pair with Cell Line/Organoid/PDX Specimen_Type.",
            needs_human_review=True,
        )

    if not is_na_like(rna_source) and is_na_like(tissue):
        # Low/medium because isolated cell sources may not always provide tissue.
        w.add(
            row,
            "R013",
            "RNA_Source present but Tissue missing/NA",
            "Medium",
            "Missing related field",
            ["RNA_Source", "Tissue"],
            "Review Tissue if RNA_Source implies an anatomical origin.",
            "RNA_Source is specific but Tissue is missing or NA.",
        )


def validate_experimental_setting_model(row: pd.Series, w: IssueWriter) -> None:
    setting = get(row, "Experimental_Setting")
    model = get(row, "Model_Type")
    sample_type = get(row, "SampleType")
    specimen = get(row, "Specimen_Type")

    if eq(setting, "In Vivo") and in_set(model, {"Cell Line", "Induced Pluripotent Stem Cells (iPSCs)", "Primary Cells", "Organoid"}):
        w.add(
            row,
            "R020",
            "In Vivo conflicts with in vitro/ex vivo Model_Type",
            "High",
            "Cross-agent conflict",
            ["Experimental_Setting", "Model_Type", "SampleType", "Specimen_Type"],
            "Review Experimental_Setting and Model_Type. If implanted cell lines are used, CDX/Xenograft may be appropriate.",
            "Experimental_Setting is In Vivo but Model_Type is a culture/cell model.",
            needs_human_review=True,
        )

    if eq(setting, "In Vitro") and in_set(model, {"Tissue", "PDX (Patient-Derived Xenograft)", "CDX (Cell Line-Derived Xenograft)", "Xenograft", "Transgenic Model", "Knockout", "Conditional Knockout", "Chemical Induced Disease Model"}):
        w.add(
            row,
            "R021",
            "In Vitro conflicts with in vivo Model_Type",
            "High",
            "Cross-agent conflict",
            ["Experimental_Setting", "Model_Type", "SampleType", "Specimen_Type"],
            "Review Experimental_Setting and Model_Type.",
            "Experimental_Setting is In Vitro but Model_Type is usually in vivo.",
            needs_human_review=True,
        )

    if eq(setting, "Ex Vivo") and in_set(sample_type, {"Cell Line"}):
        w.add(
            row,
            "R022",
            "Ex Vivo conflicts with Cell Line SampleType",
            "Medium",
            "Cross-agent conflict",
            ["Experimental_Setting", "SampleType", "Specimen_Type", "Model_Type"],
            "Review whether this is ex vivo primary material or in vitro cell culture.",
            "Ex vivo material is usually freshly isolated tissue/cells rather than established cell line.",
        )


def validate_perturbation_internal(row: pd.Series, w: IssueWriter) -> None:
    gse_pert = get(row, "GSE_Pert")
    gsm_pert = get(row, "GSM_Pert")
    pert = get(row, "Pert")
    dose = get(row, "Pert_Dose")
    freq = get(row, "Pert_Freq")
    dur = get(row, "Pert_Duration")
    route = get(row, "Route_Admin")

    if eq(gse_pert, "No") and (eq(gsm_pert, "Perturbed") or not is_na_like(pert)):
        w.add(
            row,
            "R030",
            "GSE_Pert No conflicts with GSM perturbation fields",
            "High",
            "Cross-agent conflict",
            ["GSE_Pert", "GSM_Pert", "Pert", "Pert_Dose", "Pert_Duration", "Route_Admin"],
            "Review GSE_Pert and GSM-level perturbation fields.",
            "Study-level perturbation is No but sample-level fields indicate perturbation.",
            needs_human_review=True,
        )

    if eq(gse_pert, "Yes") and is_na_like(gsm_pert):
        w.add(
            row,
            "R031",
            "GSE_Pert Yes but GSM_Pert missing/NA",
            "Medium",
            "Missing related field",
            ["GSE_Pert", "GSM_Pert", "Pert"],
            "Review whether GSM sample is Perturbed or Control.",
            "Perturbation study requires sample-level perturbation status.",
        )

    if eq(gsm_pert, "Perturbed") and is_na_like(pert):
        w.add(
            row,
            "R032",
            "GSM_Pert Perturbed but Pert missing/NA",
            "High",
            "Missing related field",
            ["GSM_Pert", "Pert", "Pert_Dose", "Pert_Duration", "Route_Admin"],
            "Review GSM_Info to extract the perturbation.",
            "Sample is marked perturbed but no perturbation agent/name was captured.",
        )

    if is_na_like(pert) and (not is_na_like(dose) or not is_na_like(freq) or not is_na_like(dur) or not is_na_like(route)):
        w.add(
            row,
            "R033",
            "Dose/frequency/duration/route present but Pert missing",
            "High",
            "Cross-agent conflict",
            ["Pert", "Pert_Dose", "Pert_Freq", "Pert_Duration", "Route_Admin"],
            "Review perturbation fields and align Pert with dose/frequency/duration/route.",
            "Treatment details exist but Pert is NA/missing.",
        )


def validate_demographics(row: pd.Series, w: IssueWriter) -> None:
    sample_type = get(row, "SampleType")
    race = get(row, "Race")
    ethnicity = get(row, "Ethnicity")
    age = get(row, "Age")
    sex = get(row, "Sex")
    tissue = get(row, "Tissue")
    rna_source = get(row, "RNA_Source")

    if not in_set(sample_type, {"Patient Specimen"}) and (not is_na_like(race) or not is_na_like(ethnicity)):
        w.add(
            row,
            "R040",
            "Race/Ethnicity present for non-patient sample",
            "Medium",
            "Cross-agent conflict",
            ["SampleType", "Race", "Ethnicity"],
            "Review Race/Ethnicity applicability. Usually NA for non-patient specimens unless donor metadata is explicit.",
            "Race/Ethnicity should generally apply only to Patient Specimen samples.",
        )

    if in_set(sample_type, {"Patient Specimen"}) and (is_blank(race) or is_blank(ethnicity)):
        w.add(
            row,
            "R041",
            "Patient Specimen has blank Race/Ethnicity",
            "Medium",
            "Missing related field",
            ["SampleType", "Race", "Ethnicity"],
            "Use Not Specified if missing from patient metadata, not blank.",
            "Patient Specimen should normally have Race/Ethnicity annotated or Not Specified.",
            suggested_field="Race/Ethnicity",
            suggested_value="Not Specified",
        )

    sex_low = lower_value(sex)
    source_text = f"{tissue} {rna_source}"
    if sex_low in {"sex: female", "female"} and has_any(source_text, MALE_TISSUES):
        w.add(
            row,
            "R042",
            "Female sex conflicts with male-specific tissue",
            "High",
            "Biological plausibility conflict",
            ["Sex", "Tissue", "RNA_Source"],
            "Review Sex and Tissue/RNA_Source.",
            "Sex is Female but tissue/source suggests male-specific anatomy.",
            needs_human_review=True,
        )

    if sex_low in {"sex: male", "male"} and has_any(source_text, FEMALE_TISSUES):
        w.add(
            row,
            "R043",
            "Male sex conflicts with female-specific tissue",
            "High",
            "Biological plausibility conflict",
            ["Sex", "Tissue", "RNA_Source"],
            "Review Sex and Tissue/RNA_Source.",
            "Sex is Male but tissue/source suggests female-specific anatomy.",
            needs_human_review=True,
        )

    if in_set(sample_type, {"Cell Line"}) and not is_na_like(age):
        w.add(
            row,
            "R044",
            "Age present for Cell Line",
            "Low",
            "Applicability review",
            ["SampleType", "Age", "GSM_Info"],
            "Review whether donor age is explicitly available; otherwise Age should usually be NA.",
            "Cell line samples generally do not have biological age unless donor age is explicitly provided.",
        )


def validate_disease_tissue(row: pd.Series, w: IssueWriter) -> None:
    disease = get(row, "Disease")
    tissue = get(row, "Tissue")
    rna_source = get(row, "RNA_Source")

    source_text = f"{tissue} {rna_source}"
    if eq(disease, "Normal") and has_any(source_text, TUMOR_TERMS):
        w.add(
            row,
            "R050",
            "Disease Normal conflicts with tumor/cancer tissue/source",
            "High",
            "Biological plausibility conflict",
            ["Disease", "Tissue", "RNA_Source"],
            "Review whether this is Normal, Adjacent Normal, or disease/tumor sample.",
            "Disease is Normal but tissue/source contains tumor/cancer terminology.",
            needs_human_review=True,
        )

    if (eq(disease, "No Disease Mentioned") or is_na_like(disease)) and has_any(source_text, TUMOR_TERMS):
        w.add(
            row,
            "R051",
            "Disease missing/No Disease Mentioned but tumor/cancer source exists",
            "High",
            "Missing related field",
            ["Disease", "Tissue", "RNA_Source"],
            "Review Disease; tumor/cancer terms in source may support a specific disease or tumor annotation.",
            "Disease is absent/conservative while tissue/source suggests diseased material.",
        )


def validate_organism_strain(row: pd.Series, w: IssueWriter) -> None:
    organism = get(row, "Organism")
    strain = get(row, "Strain")
    if eq(organism, "Homo sapiens") and not is_na_like(strain):
        w.add(
            row,
            "R060",
            "Human sample has non-NA Strain",
            "Medium",
            "Cross-agent conflict",
            ["Organism", "Strain"],
            "Review Strain; strain is usually relevant to model organisms, not human samples.",
            "Organism is Homo sapiens but Strain contains a value.",
        )


RULES: List[Callable[[pd.Series, IssueWriter], None]] = [
    validate_seq_type_rna_library,
    validate_rna_source_tissue_sampletype,
    validate_experimental_setting_model,
    validate_perturbation_internal,
    validate_demographics,
    validate_disease_tissue,
    validate_organism_strain,
]


def validate_cross_agent(df: pd.DataFrame, config: ValidationConfig) -> pd.DataFrame:
    if config.gse_col not in df.columns or config.gsm_col not in df.columns:
        raise ValueError(f"Input must contain {config.gse_col} and {config.gsm_col}.")

    writer = IssueWriter(df=df, config=config)
    for _, row in df.iterrows():
        for rule in RULES:
            rule(row, writer)
    return writer.dataframe()


def build_rule_summary(issues_df: pd.DataFrame) -> pd.DataFrame:
    if issues_df.empty:
        return pd.DataFrame(columns=["Rule_ID", "Rule_Name", "Severity", "N_Issues", "N_GSE", "N_GSM"])
    return (
        issues_df.groupby(["Rule_ID", "Rule_Name", "Severity"], dropna=False)
        .agg(N_Issues=("Issue_ID", "count"), N_GSE=("GSE_ID", "nunique"), N_GSM=("GSM_ID", "nunique"))
        .reset_index()
        .sort_values(["Severity", "N_Issues"], ascending=[True, False], kind="stable")
    )


def build_gse_summary(issues_df: pd.DataFrame) -> pd.DataFrame:
    if issues_df.empty:
        return pd.DataFrame(columns=["GSE_ID", "N_Issues", "N_High", "N_Medium", "N_Low", "Rules"])
    out = (
        issues_df.assign(
            Is_High=lambda d: d["Severity"].eq("High"),
            Is_Medium=lambda d: d["Severity"].eq("Medium"),
            Is_Low=lambda d: d["Severity"].eq("Low"),
        )
        .groupby("GSE_ID", dropna=False)
        .agg(
            N_Issues=("Issue_ID", "count"),
            N_High=("Is_High", "sum"),
            N_Medium=("Is_Medium", "sum"),
            N_Low=("Is_Low", "sum"),
            Rules=("Rule_ID", lambda x: "; ".join(sorted(set(map(str, x))))),
        )
        .reset_index()
        .sort_values(["N_High", "N_Issues"], ascending=[False, False], kind="stable")
    )
    return out


def write_outputs(df: pd.DataFrame, issues_df: pd.DataFrame, output_report: Path) -> None:
    output_report.parent.mkdir(parents=True, exist_ok=True)
    rule_summary = build_rule_summary(issues_df)
    gse_summary = build_gse_summary(issues_df)

    with pd.ExcelWriter(output_report, engine="openpyxl") as writer:
        issues_df.to_excel(writer, index=False, sheet_name="Cross_Agent_Issues")
        rule_summary.to_excel(writer, index=False, sheet_name="Rule_Summary")
        gse_summary.to_excel(writer, index=False, sheet_name="GSE_Summary")
        df.to_excel(writer, index=False, sheet_name="Input_Unchanged")


def main() -> None:
    parser = argparse.ArgumentParser(description="GEOMeta Stage 1.6 cross-agent/cross-field validation")
    parser.add_argument("--input", required=True, help="Stage 1.5 corrected Stage 1 file")
    parser.add_argument("--sheet-name", default=None, help="Excel sheet name; defaults to first sheet")
    parser.add_argument("--output-dir", required=True, help="Output directory")
    parser.add_argument("--run-version", required=True, help="Run version prefix")
    parser.add_argument("--gse-col", default="GSE_ID")
    parser.add_argument("--gsm-col", default="GSM_ID")
    parser.add_argument("--include-low-severity", action="store_true")
    parser.add_argument("--max-context-chars", type=int, default=1200)
    args = parser.parse_args()

    input_path = Path(args.input).resolve()
    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    df = read_table(input_path, sheet_name=args.sheet_name)
    cfg = ValidationConfig(
        gse_col=args.gse_col,
        gsm_col=args.gsm_col,
        max_context_chars=args.max_context_chars,
        include_low_severity=args.include_low_severity,
    )

    print(f"Reading Stage 1/1.5 file: {input_path}")
    print(f"Rows: {len(df):,}; columns: {len(df.columns):,}")
    issues_df = validate_cross_agent(df, cfg)

    report_path = output_dir / f"{args.run_version}_stage1_qa2_cross_agent_validation_report.xlsx"
    write_outputs(df, issues_df, report_path)

    print("Done.")
    print(f"Cross-agent issues: {len(issues_df):,}")
    if not issues_df.empty:
        print(issues_df["Severity"].value_counts(dropna=False).to_string())
    print(f"Report: {report_path}")


if __name__ == "__main__":
    main()
